### ISSUE TITLE
Crash on Liteloader 1.11.2-SNAPSHOT-r5388132-b10-10

### ISSUE THREAD

**Issue by AlexHalogen** [uyjulian/MinecraftX-RAY#6]
The xraymod crashes on the latest liteloader snapshot release(1.11.2-SNAPSHOT-r5388132-b10-10)
Error information from latest.log says:

```
[10:40:54] [Client thread/FATAL]: Mixin apply failed mixins.uyjuliansXrayMod.json:MixinBlockModelRenderer -> brc: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method a in mixins.uyjuliansXrayMod.json:MixinBlockModelRenderer was not located in the target class
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method a in mixins.uyjuliansXrayMod.json:MixinBlockModelRenderer was not located in the target class
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:325) ~[liteloader-1.11.2-SNAPSHOT.jar:1.11.2-SNAPSHOT+jnks-b10.git-53881326bb43260c8bc710c8de49d289a988dccb]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:292) ~[liteloader-1.11.2-SNAPSHOT.jar:1.11.2-SNAPSHOT+jnks-b10.git-53881326bb43260c8bc710c8de49d289a988dccb]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:229) ~[liteloader-1.11.2-SNAPSHOT.jar:1.11.2-SNAPSHOT+jnks-b10.git-53881326bb43260c8bc710c8de49d289a988dccb]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:203) ~[liteloader-1.11.2-SNAPSHOT.jar:1.11.2-SNAPSHOT+jnks-b10.git-53881326bb43260c8bc710c8de49d289a988dccb]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:186) ~[liteloader-1.11.2-SNAPSHOT.jar:1.11.2-SNAPSHOT+jnks-b10.git-53881326bb43260c8bc710c8de49d289a988dccb]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1103) ~[liteloader-1.11.2-SNAPSHOT.jar:1.11.2-SNAPSHOT+jnks-b10.git-53881326bb43260c8bc710c8de49d289a988dccb]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:245) ~[liteloader-1.11.2-SNAPSHOT.jar:1.11.2-SNAPSHOT+jnks-b10.git-53881326bb43260c8bc710c8de49d289a988dccb]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:281) ~[liteloader-1.11.2-SNAPSHOT.jar:1.11.2-SNAPSHOT+jnks-b10.git-53881326bb43260c8bc710c8de49d289a988dccb]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:816) [liteloader-1.11.2-SNAPSHOT.jar:1.11.2-SNAPSHOT+jnks-b10.git-53881326bb43260c8bc710c8de49d289a988dccb]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:786) [liteloader-1.11.2-SNAPSHOT.jar:1.11.2-SNAPSHOT+jnks-b10.git-53881326bb43260c8bc710c8de49d289a988dccb]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:591) [liteloader-1.11.2-SNAPSHOT.jar:1.11.2-SNAPSHOT+jnks-b10.git-53881326bb43260c8bc710c8de49d289a988dccb]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:183) [liteloader-1.11.2-SNAPSHOT.jar:1.11.2-SNAPSHOT+jnks-b10.git-53881326bb43260c8bc710c8de49d289a988dccb]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_60]
	at bra.<init>(SourceFile:29) [bra.class:?]
	at bes.an(SourceFile:532) [bes.class:?]
	at bes.a(SourceFile:383) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[10:40:54] [Client thread/INFO]: [STDERR]: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.uyjuliansXrayMod.json:MixinBlockModelRenderer] from phase [DEFAULT] in config [mixins.uyjuliansXrayMod.json] FAILED during APPLY
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:882)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:835)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:595)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:183)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at bra.<init>(SourceFile:29)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at bes.an(SourceFile:532)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at bes.a(SourceFile:383)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:40:54] [Client thread/INFO]: [STDERR]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method a in mixins.uyjuliansXrayMod.json:MixinBlockModelRenderer was not located in the target class
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:325)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:292)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:229)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:203)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:186)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1103)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:245)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:281)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:816)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:786)
[10:40:54] [Client thread/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:591)
[10:40:54] [Client thread/INFO]: [STDERR]: 	... 15 more
```

**Comment by uyjulian** [comment]
This mod currently is conflicting with Optifine.

--
~Julian Uy
